### ISSUE TITLE
inconsistent game dates and game keys

### ISSUE THREAD

**Issue by bdilday** [chadwickbureau/retrosheet#21]
The following game keys are not consistent with the game date. As far as I can tell this affects the team-specific event files but not the game logs.

```
game.date  game.key
1919-08-08 CIN191908100
1929-07-29 WS1192907250
1962-06-01 MLN196207010
7155-05-07 NY1195505070
```

**Comment by tturocy** [comment]
This isn't anything for us - issues with the underlying data should be reported directly to Retrosheet as we only provide this repository as a convenience.  I have forwarded this on to them in this instance.
