### ISSUE TITLE
Add reorganized/additional NLB data

### ISSUE THREAD

**Issue by droher** [chadwickbureau/retrosheet#32]
I noticed that the NLB data in the repo hasn't been updated since Jan 2021 - Retrosheet has since added a bunch of new games and organized them in a more regular way: https://www.retrosheet.org/NegroLeagues/NgLgDownloads.html

I'd be happy to submit a PR to add them.

**Comment by tturocy** [comment]
So far the Negro Leagues data are considered provisional and therefore not included.  This will change in due course.
