### ISSUE TITLE
What team is BL3

### ISSUE THREAD

**Issue by mohataher** [chadwickbureau/retrosheet#6]
I made a parser that parses teams and gamelogs. I noticed there was no definition of team BL3 in data on the repository. Even in [team codes](http://www.retrosheet.org/team_codes.html), I couldn't find it. Any suggestions?

**Comment by tturocy** [comment]
This is a Retrosheet issue.

**Comment by mohataher** [comment]
Just in case someone else had the same issue, I had a look at [park code file](https://github.com/chadwickbureau/retrosheet/blob/5ade5b1028cbd1251ce182cca228c40a6b905dcc/misc/parkcode.txt) and found out it's Baltimore Orioles. Somehow, the ID of teams change in some years and it's descirbed in notes column in the file. 

This is just my opinion and not sure if it's 100% accurate.
